"""
YouTube cookie extraction using Playwright.

Uses a persistent Chromium profile to maintain Google login state.
Exports cookies in Netscape format for yt-dlp consumption.

Usage:
  1. First run: call setup_profile() — opens a visible browser for manual Google login.
  2. After that: call get_cookies_for_ytdlp() — headless extraction, returns cookies.txt path.

The persistent profile lives at PROFILE_DIR and survives restarts.
"""

import os
import logging
import asyncio

logger = logging.getLogger(__name__)

# Persistent browser profile directory
PROFILE_DIR = os.environ.get(
    "YT_COOKIE_PROFILE_DIR",
    os.path.join(os.path.expanduser("~"), ".yt-cookie-profile"),
)

# Default output path for the cookies file
DEFAULT_COOKIES_PATH = os.environ.get(
    "YT_COOKIES_PATH",
    os.path.join(os.path.expanduser("~"), ".yt-cookies", "cookies.txt"),
)


def _to_netscape(cookies: list) -> str:
    """Convert Playwright cookies list to Netscape/Mozilla cookies.txt format."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by youtube_cookies.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        # Netscape format: domain, include_subdomains, path, secure, expires, name, value
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = str(int(c.get("expires", 0)))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


async def setup_profile(headless: bool = False) -> None:
    """Open a browser window for manual Google/YouTube login.

    This creates or reuses a persistent Chromium profile. After logging in,
    simply close the browser window — the session is saved to disk.

    Args:
        headless: If False (default), opens a visible browser window.
    """
    from playwright.async_api import async_playwright

    os.makedirs(PROFILE_DIR, exist_ok=True)

    async with async_playwright() as p:
        context = await p.chromium.launch_persistent_context(
            user_data_dir=PROFILE_DIR,
            headless=headless,
            args=["--disable-blink-features=AutomationControlled"],
            ignore_default_args=["--enable-automation"],
        )
        page = context.pages[0] if context.pages else await context.new_page()

        # Navigate to YouTube login
        await page.goto("https://accounts.google.com/ServiceLogin?service=youtube")

        logger.info(
            "Browser opened. Please log into your Google account.\n"
            "After logging in, navigate to https://www.youtube.com to confirm access, "
            "then close the browser window."
        )

        # Wait until the browser is closed by the user
        try:
            await page.wait_for_event("close", timeout=600_000)  # 10 min
        except Exception:
            pass

        await context.close()

    logger.info(f"Profile saved to {PROFILE_DIR}")


async def extract_cookies(output_path: str | None = None) -> str:
    """Extract YouTube cookies from the persistent profile.

    Launches headless Chromium with the saved profile, navigates to
    youtube.com/robots.txt (prevents cookie rotation), extracts cookies,
    and writes them in Netscape format.

    Args:
        output_path: Where to save cookies.txt. Defaults to DEFAULT_COOKIES_PATH.

    Returns:
        Absolute path to the written cookies.txt file.

    Raises:
        RuntimeError: If no profile exists (run setup_profile first) or
                      no YouTube cookies were found.
    """
    from playwright.async_api import async_playwright

    if not os.path.isdir(PROFILE_DIR):
        raise RuntimeError(
            f"No browser profile found at {PROFILE_DIR}. "
            "Run setup_profile() first to log into Google."
        )

    output_path = output_path or DEFAULT_COOKIES_PATH
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    async with async_playwright() as p:
        context = await p.chromium.launch_persistent_context(
            user_data_dir=PROFILE_DIR,
            headless=True,
            args=["--disable-blink-features=AutomationControlled"],
            ignore_default_args=["--enable-automation"],
        )

        page = context.pages[0] if context.pages else await context.new_page()

        # Navigate to robots.txt to get cookies without triggering rotation
        await page.goto("https://www.youtube.com/robots.txt", wait_until="networkidle")
        # Small wait to ensure all cookies are set
        await page.wait_for_timeout(2000)

        # Extract all cookies for youtube.com
        all_cookies = await context.cookies("https://www.youtube.com")

        await context.close()

    if not all_cookies:
        raise RuntimeError(
            "No YouTube cookies found. The profile may not be logged in. "
            "Run setup_profile() to log in again."
        )

    # Filter to youtube.com cookies only
    yt_cookies = [
        c for c in all_cookies
        if "youtube.com" in c.get("domain", "") or "google.com" in c.get("domain", "")
    ]

    if not yt_cookies:
        raise RuntimeError("No YouTube/Google cookies found in the profile.")

    netscape_content = _to_netscape(yt_cookies)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(netscape_content)

    logger.info(f"Exported {len(yt_cookies)} cookies to {output_path}")
    return output_path


async def get_cookies_for_ytdlp(output_path: str | None = None) -> str:
    """High-level helper: extract fresh cookies and return the file path.

    This is what Simone's Downloader should call before downloading.
    It returns a path suitable for yt-dlp's --cookies option.

    Returns:
        Path to fresh cookies.txt in Netscape format.
    """
    return await extract_cookies(output_path)


def get_cookies_sync(output_path: str | None = None) -> str:
    """Synchronous wrapper for get_cookies_for_ytdlp."""
    return asyncio.run(get_cookies_for_ytdlp(output_path))


# --- CLI entrypoint ---
if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if len(sys.argv) > 1 and sys.argv[1] == "setup":
        print("Opening browser for YouTube login...")
        print("Log in, then close the browser window.")
        asyncio.run(setup_profile(headless=False))
        print(f"\nProfile saved to {PROFILE_DIR}")
        print("You can now run this script without 'setup' to extract cookies.")
    else:
        try:
            path = get_cookies_sync()
            print(f"Cookies exported to: {path}")
        except RuntimeError as e:
            print(f"Error: {e}")
            print("\nRun with 'setup' argument first:")
            print(f"  python {sys.argv[0]} setup")
            sys.exit(1)
